### ISSUE TITLE
Source maps? Minify?

### ISSUE THREAD

**Issue by michaeljcoyne** [langemike/laravel5-less#4]
Is this capable of generating source maps?

And minifying?   

You could do minifying through gulp - it is more the source maps I am interested in.

Thanks.

**Comment by langemike** [comment]
Yes, sourcemaps works. And is provided through oyejorge Less compiler.

I provided it as an option in the options parameter on the compile method (second argument).

So example like this:
Less::compile('filename', array('sourceMap' => true));

Or you could provide LESS_SOURCEMAP = true in your .env file.

I still need to merge a pull request to support minifying. But i'm a little bit busy these last weeks. I try to do it ASAP.

**Comment by michaeljcoyne** [comment]
Thanks I have seen this now.
